# Generated by Django 5.2 on 2025-04-17 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.CharField(blank=True, max_length=10)),
                ('perosonality', models.TextField()),
                ('backstory', models.TextField(blank=True)),
                ('fear', models.TextField(blank=True)),
                ('dream', models.TextField(blank=True)),
                ('secret', models.TextField(blank=True)),
            ],
        ),
    ]
