# Generated by Django 5.2 on 2025-04-18 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='characterprofile',
            old_name='perosonality',
            new_name='personality',
        ),
    ]
